### ISSUE TITLE
Error UnhandledPromiseRejectionWarning on Windows 10

### ISSUE THREAD

**Issue by diguifi** [siddharthkp/rest-your-eyes#3]
Tried it on Windows 10 x64, dual screen, didn't work, does anybody know what might be causing this? Is this pack compatible with Windows?

Here's the error:
```
(node:9516) UnhandledPromiseRejectionWarning: Error: Exit code: 2147749900. N� - XXXXXX
ERRO:
Description = No Support

    at ChildProcess.<anonymous> (C:\Users\xxxxxxxxxxx\AppData\Roaming\nvm\v10.10.0\node_modules\rest-your-eyes\node_modules\wmi-client\lib\wmic.js:169:22)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
(node:9516) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9516) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by bsides** [comment]
Not a maintainer or anything but the error describes it:

> Description = No Support

In the other hand, [the library it uses](https://github.com/kevva/brightness) seems to support Windows but both are pretty old now so the support may be weak 😞
